// constants/index.ts
import { PropertyProps, ReviewProps } from "@/interfaces";

// --- Data for Hero Section (from Milestone 0, keeping for completeness) ---
export const HERO_BG_IMAGE = "https://picsum.photos/seed/hero/1920/1080";

export const FILTER_LABELS = [
  "All",
  "Luxury Villa",
  "Mountain View",
  "Desert View",
  "City View",
  "Riverside",
  "Beachfront",
  "Lakeside",
  "Garden",
  "City Center",
  "Secluded",
  "Cliffside",
  "Historical",
  "Safari",
  "Countryside",
  "Riverfront",
  "Ski",
  "Island Paradise",
  "Ocean View",
];

// --- Property Listing Sample Data (NEW for Milestone 3) ---
// Note: The 'image' field in the sample provided uses example.com,
// which won't display. I've replaced them with picsum.photos for actual display.
// I've also added 'id', 'description', 'images', and 'reviews' to each property
// to match the PropertyProps interface and the requirements for the detail page.
export const PROPERTY_LISTING_SAMPLE: PropertyProps[] = [
  {
    id: "villa-ocean-breeze", // Using a slug based on name for ID
    name: "Villa Ocean Breeze",
    address: {
      state: "Seminyak",
      city: "Bali",
      country: "Indonesia",
    },
    rating: 4.89,
    category: ["Luxury Villa", "Pool", "Free Parking"],
    price: 3200,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-6",
    },
    image: "https://picsum.photos/seed/villa-ocean-breeze-main/800/600", // Placeholder image
    images: [ // Additional images for gallery
      "https://picsum.photos/seed/villa-ocean-breeze-1/1200/800",
      "https://picsum.photos/seed/villa-ocean-breeze-2/1200/800",
      "https://picsum.photos/seed/villa-ocean-breeze-3/1200/800",
      "https://picsum.photos/seed/villa-ocean-breeze-4/1200/800",
    ],
    description: "A stunning luxury villa with breathtaking ocean views, private pool, and spacious living areas. Perfect for a relaxing getaway in Bali.",
    discount: "",
    reviews: [
      { name: "Alice B.", avatar: "https://picsum.photos/seed/avatar1/50/50", rating: 5, comment: "Absolutely beautiful place! Highly recommend." },
      { name: "John D.", avatar: "https://picsum.photos/seed/avatar2/50/50", rating: 4, comment: "Great location and amenities, though a bit pricey." },
    ],
  },
  {
    id: "mountain-escape-chalet",
    name: "Mountain Escape Chalet",
    address: {
      state: "Aspen",
      city: "Colorado",
      country: "USA",
    },
    rating: 4.70,
    category: ["Mountain View", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: {
      bed: "4",
      shower: "2",
      occupants: "5-7",
    },
    image: "https://picsum.photos/seed/mountain-chalet-main/800/600",
    images: [
      "https://picsum.photos/seed/mountain-chalet-1/1200/800",
      "https://picsum.photos/seed/mountain-chalet-2/1200/800",
      "https://picsum.photos/seed/mountain-chalet-3/1200/800",
    ],
    description: "Cozy chalet nestled in the mountains of Aspen. Ideal for ski trips or summer hiking adventures with stunning views.",
    discount: "30",
    reviews: [
      { name: "Emily R.", avatar: "https://picsum.photos/seed/avatar3/50/50", rating: 5, comment: "Perfect mountain retreat! Warm and inviting." },
      { name: "Mike S.", avatar: "https://picsum.photos/seed/avatar4/50/50", rating: 4, comment: "Ski-in/ski-out access was great. Would stay again." },
    ],
  },
  {
    id: "cozy-desert-retreat",
    name: "Cozy Desert Retreat",
    address: {
      state: "Palm Springs",
      city: "California",
      country: "USA",
    },
    rating: 4.92,
    category: ["Desert View", "Pet Friendly", "Self Checkin"],
    price: 1500,
    offers: {
      bed: "2",
      shower: "1",
      occupants: "2-3",
    },
    image: "https://picsum.photos/seed/desert-retreat-main/800/600",
    images: [
      "https://picsum.photos/seed/desert-retreat-1/1200/800",
      "https://picsum.photos/seed/desert-retreat-2/1200/800",
    ],
    description: "A peaceful and private desert escape with beautiful views and pet-friendly amenities. Perfect for a quiet getaway.",
    discount: "",
    reviews: [
      { name: "Sarah J.", avatar: "https://picsum.photos/seed/avatar5/50/50", rating: 5, comment: "Loved the tranquility and the sunsets!" },
      { name: "David L.", avatar: "https://picsum.photos/seed/avatar6/50/50", rating: 5, comment: "Our dog loved it too. Very clean." },
    ],
  },
  {
    id: "city-lights-penthouse",
    name: "City Lights Penthouse",
    address: {
      state: "New York",
      city: "New York",
      country: "USA",
    },
    rating: 4.85,
    category: ["City View", "Free WiFi", "24h Checkin"],
    price: 4500,
    offers: {
      bed: "2",
      shower: "2",
      occupants: "2-4",
    },
    image: "https://picsum.photos/seed/city-penthouse-main/800/600",
    images: [
      "https://picsum.photos/seed/city-penthouse-1/1200/800",
      "https://picsum.photos/seed/city-penthouse-2/1200/800",
      "https://picsum.photos/seed/city-penthouse-3/1200/800",
    ],
    description: "Experience the vibrant energy of New York City from this luxurious penthouse. Breathtaking views and central location.",
    discount: "15",
    reviews: [
      { name: "Chris T.", avatar: "https://picsum.photos/seed/avatar7/50/50", rating: 4, comment: "Amazing views, slightly noisy but expected for NYC." },
      { name: "Maria K.", avatar: "https://picsum.photos/seed/avatar8/50/50", rating: 5, comment: "The best place to stay in the city! So elegant." },
    ],
  },
  {
    id: "riverside-cabin",
    name: "Riverside Cabin",
    address: {
      state: "Queenstown",
      city: "Otago",
      country: "New Zealand",
    },
    rating: 4.77,
    category: ["Riverside", "Private Dock", "Free Kayaks"],
    price: 2800,
    offers: {
      bed: "3",
      shower: "2",
      occupants: "4-6",
    },
    image: "https://picsum.photos/seed/riverside-cabin-main/800/600",
    images: [
      "https://picsum.photos/seed/riverside-cabin-1/1200/800",
      "https://picsum.photos/seed/riverside-cabin-2/1200/800",
    ],
    description: "A charming cabin by the river, offering tranquility and direct access to water activities. Perfect for nature lovers.",
    discount: "20",
    reviews: [
      { name: "Oliver P.", avatar: "https://picsum.photos/seed/avatar9/50/50", rating: 5, comment: "Absolutely serene. The kayaks were a huge bonus!" },
      { name: "Sophie G.", avatar: "https://picsum.photos/seed/avatar10/50/50", rating: 4, comment: "Beautiful spot, slightly remote but worth it." },
    ],
  },
  {
    id: "modern-beachfront-villa",
    name: "Modern Beachfront Villa",
    address: {
      state: "Sidemen",
      city: "Bali",
      country: "Indonesia",
    },
    rating: 4.95,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 5000,
    offers: {
      bed: "5",
      shower: "4",
      occupants: "8-10",
    },
    image: "https://picsum.photos/seed/beachfront-villa-main/800/600",
    images: [
      "https://picsum.photos/seed/beachfront-villa-1/1200/800",
      "https://picsum.photos/seed/beachfront-villa-2/1200/800",
      "https://picsum.photos/seed/beachfront-villa-3/1200/800",
    ],
    description: "Luxurious beachfront villa with stunning ocean views, a private infinity pool, and dedicated chef service.",
    discount: "",
    reviews: [
      { name: "Liam C.", avatar: "https://picsum.photos/seed/avatar11/50/50", rating: 5, comment: "Unforgettable experience! The chef service was amazing." },
      { name: "Grace H.", avatar: "https://picsum.photos/seed/avatar12/50/50", rating: 5, comment: "Pure paradise. Can't wait to come back." },
    ],
  },
  {
    id: "lakeside-chalet",
    name: "Lakeside Chalet",
    address: {
      state: "Banff",
      city: "Alberta",
      country: "Canada",
    },
    rating: 4.65,
    category: ["Lakeside", "Mountain View", "Hiking Trails"],
    price: 2300,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-5",
    },
    image: "https://picsum.photos/seed/lakeside-chalet-main/800/600",
    images: [
      "https://picsum.photos/seed/lakeside-chalet-1/1200/800",
      "https://picsum.photos/seed/lakeside-chalet-2/1200/800",
    ],
    description: "Charming chalet by the lake with stunning mountain views and direct access to hiking trails. Perfect for outdoor enthusiasts.",
    discount: "10",
    reviews: [
      { name: "Noah W.", avatar: "https://picsum.photos/seed/avatar13/50/50", rating: 4, comment: "Beautiful scenery and great hiking. Chalet was comfortable." },
      { name: "Ava F.", avatar: "https://picsum.photos/seed/avatar14/50/50", rating: 5, comment: "Idyllic location. Loved waking up to the lake view." },
    ],
  },
  {
    id: "tropical-garden-villa",
    name: "Tropical Garden Villa",
    address: {
      state: "Koh Samui",
      city: "Surat Thani",
      country: "Thailand",
    },
    rating: 4.80,
    category: ["Garden", "Free Parking", "Self Checkin"],
    price: 2750,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "5-6",
    },
    image: "https://picsum.photos/seed/tropical-garden-main/800/600",
    images: [
      "https://picsum.photos/seed/tropical-garden-1/1200/800",
      "https://picsum.photos/seed/tropical-garden-2/1200/800",
    ],
    description: "A serene villa set within a lush tropical garden, offering peace and privacy. Great for families.",
    discount: "25",
    reviews: [
      { name: "Mia V.", avatar: "https://picsum.photos/seed/avatar15/50/50", rating: 5, comment: "Beautiful garden and very peaceful. Great value." },
      { name: "Ethan B.", avatar: "https://picsum.photos/seed/avatar16/50/50", rating: 4, comment: "Good facilities, but a bit far from the main attractions." },
    ],
  },
  {
    id: "urban-loft",
    name: "Urban Loft",
    address: {
      state: "Berlin",
      city: "Berlin",
      country: "Germany",
    },
    rating: 4.60,
    category: ["City Center", "Free WiFi", "24h Checkin"],
    price: 2000,
    offers: {
      bed: "2",
      shower: "1",
      occupants: "2-3",
    },
    image: "https://picsum.photos/seed/urban-loft-main/800/600",
    images: [
      "https://picsum.photos/seed/urban-loft-1/1200/800",
      "https://picsum.photos/seed/urban-loft-2/1200/800",
    ],
    description: "Stylish urban loft in the heart of Berlin, perfect for exploring the city's vibrant culture and nightlife.",
    discount: "",
    reviews: [
      { name: "Lucas M.", avatar: "https://picsum.photos/seed/avatar17/50/50", rating: 4, comment: "Very modern and central. Easy to get around." },
      { name: "Chloe S.", avatar: "https://picsum.photos/seed/avatar18/50/50", rating: 3, comment: "Nice design but the area was a bit loud at night." },
    ],
  },
  {
    id: "secluded-forest-cabin",
    name: "Secluded Forest Cabin",
    address: {
      state: "Whistler",
      city: "British Columbia",
      country: "Canada",
    },
    rating: 4.72,
    category: ["Secluded", "Hot Tub", "Self Checkin"],
    price: 2600,
    offers: {
      bed: "4",
      shower: "2",
      occupants: "5-7",
    },
    image: "https://picsum.photos/seed/forest-cabin-main/800/600",
    images: [
      "https://picsum.photos/seed/forest-cabin-1/1200/800",
      "https://picsum.photos/seed/forest-cabin-2/1200/800",
    ],
    description: "A cozy and secluded cabin in the heart of the forest, complete with a hot tub. Ideal for a peaceful escape.",
    discount: "40",
    reviews: [
      { name: "Zoe K.", avatar: "https://picsum.photos/seed/avatar19/50/50", rating: 5, comment: "Loved the hot tub under the stars! So relaxing." },
      { name: "Jack P.", avatar: "https://picsum.photos/seed/avatar20/50/50", rating: 4, comment: "Very private, but a bit of a drive to town." },
    ],
  },
  {
    id: "cliffside-villa",
    name: "Cliffside Villa",
    address: {
      state: "Amalfi",
      city: "Salerno",
      country: "Italy",
    },
    rating: 4.93,
    category: ["Cliffside", "Infinity Pool", "Sea View"],
    price: 6000,
    offers: {
      bed: "4",
      shower: "4",
      occupants: "6-8",
    },
    image: "https://picsum.photos/seed/cliffside-villa-main/800/600",
    images: [
      "https://picsum.photos/seed/cliffside-villa-1/1200/800",
      "https://picsum.photos/seed/cliffside-villa-2/1200/800",
      "https://picsum.photos/seed/cliffside-villa-3/1200/800",
    ],
    description: "Perched on a cliff with an infinity pool and breathtaking sea views. The ultimate luxury experience on the Amalfi Coast.",
    discount: "50",
    reviews: [
      { name: "Daniel A.", avatar: "https://picsum.photos/seed/avatar21/50/50", rating: 5, comment: "Unbelievable views! The villa is stunning." },
      { name: "Ella N.", avatar: "https://picsum.photos/seed/avatar22/50/50", rating: 5, comment: "Worth every penny. Pure luxury." },
    ],
  },
  {
    id: "coastal-escape-villa",
    name: "Coastal Escape Villa",
    address: {
      state: "Noosa",
      city: "Queensland",
      country: "Australia",
    },
    rating: 4.83,
    category: ["Beachfront", "Pet Friendly", "Free Parking"],
    price: 3400,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-6",
    },
    image: "https://picsum.photos/seed/coastal-villa-main/800/600",
    images: [
      "https://picsum.photos/seed/coastal-villa-1/1200/800",
      "https://picsum.photos/seed/coastal-villa-2/1200/800",
    ],
    description: "A spacious beachfront villa, perfect for families with pets. Enjoy the sun and surf of the Australian coast.",
    discount: "",
    reviews: [
      { name: "Leo T.", avatar: "https://picsum.photos/seed/avatar23/50/50", rating: 4, comment: "Great for families, but beach access was a short walk." },
      { name: "Ruby F.", avatar: "https://picsum.photos/seed/avatar24/50/50", rating: 5, comment: "Loved the pet-friendly policy and the spacious living area." },
    ],
  },
  {
    id: "historical-villa",
    name: "Historical Villa",
    address: {
      state: "Florence",
      city: "Tuscany",
      country: "Italy",
    },
    rating: 4.67,
    category: ["Historical", "Free Breakfast", "Self Checkin"],
    price: 2700,
    offers: {
      bed: "2",
      shower: "2",
      occupants: "2-4",
    },
    image: "https://picsum.photos/seed/historical-villa-main/800/600",
    images: [
      "https://picsum.photos/seed/historical-villa-1/1200/800",
      "https://picsum.photos/seed/historical-villa-2/1200/800",
    ],
    description: "Step back in time in this beautiful historical villa in Tuscany. Includes free breakfast and a charming garden.",
    discount: "35",
    reviews: [
      { name: "Henry G.", avatar: "https://picsum.photos/seed/avatar25/50/50", rating: 5, comment: "Felt like living in a museum, in a good way! Very authentic." },
      { name: "Ivy P.", avatar: "https://picsum.photos/seed/avatar26/50/50", rating: 4, comment: "Beautiful architecture, but the internet was a bit slow." },
    ],
  },
  {
    id: "downtown-apartment",
    name: "Downtown Apartment",
    address: {
      state: "Tokyo",
      city: "Tokyo",
      country: "Japan",
    },
    rating: 4.81,
    category: ["City Center", "Free WiFi", "Public Transport"],
    price: 2200,
    offers: {
      bed: "1",
      shower: "1",
      occupants: "2",
    },
    image: "https://picsum.photos/seed/tokyo-apartment-main/800/600",
    images: [
      "https://picsum.photos/seed/tokyo-apartment-1/1200/800",
      "https://picsum.photos/seed/tokyo-apartment-2/1200/800",
    ],
    description: "Modern apartment in the bustling heart of Tokyo. Perfect for solo travelers or couples wanting to explore the city.",
    discount: "",
    reviews: [
      { name: "Sam N.", avatar: "https://picsum.photos/seed/avatar27/50/50", rating: 5, comment: "Amazing location, close to everything. Very clean." },
      { name: "Chloe M.", avatar: "https://picsum.photos/seed/avatar28/50/50", rating: 4, comment: "Compact but efficient. Perfect for a short city break." },
    ],
  },
  {
    id: "luxury-safari-lodge",
    name: "Luxury Safari Lodge",
    address: {
      state: "Serengeti",
      city: "Mara",
      country: "Tanzania",
    },
    rating: 4.97,
    category: ["Safari", "Guided Tours", "Free Breakfast"],
    price: 4500,
    offers: {
      bed: "4",
      shower: "4",
      occupants: "6-8",
    },
    image: "https://picsum.photos/seed/safari-lodge-main/800/600",
    images: [
      "https://picsum.photos/seed/safari-lodge-1/1200/800",
      "https://picsum.photos/seed/safari-lodge-2/1200/800",
    ],
    description: "Experience the wilderness in luxury. This lodge offers guided safari tours and stunning views of the Serengeti.",
    discount: "20",
    reviews: [
      { name: "Fred C.", avatar: "https://picsum.photos/seed/avatar29/50/50", rating: 5, comment: "Wildlife viewing was incredible! The lodge staff were exceptional." },
      { name: "Gina B.", avatar: "https://picsum.photos/seed/avatar30/50/50", rating: 5, comment: "A truly once-in-a-lifetime experience. Highly recommend." },
    ],
  },
  {
    id: "countryside-cottage",
    name: "Countryside Cottage",
    address: {
      state: "Cotswolds",
      city: "Gloucestershire",
      country: "UK",
    },
    rating: 4.58,
    category: ["Countryside", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: {
      bed: "2",
      shower: "1",
      occupants: "2-4",
    },
    image: "https://picsum.photos/seed/cottage-main/800/600",
    images: [
      "https://picsum.photos/seed/cottage-1/1200/800",
      "https://picsum.photos/seed/cottage-2/1200/800",
    ],
    description: "Charming cottage nestled in the picturesque Cotswolds. Perfect for a cozy, peaceful retreat.",
    discount: "25",
    reviews: [
      { name: "Will D.", avatar: "https://picsum.photos/seed/avatar31/50/50", rating: 4, comment: "Quaint and quiet, exactly what we needed. Fireplace was lovely." },
      { name: "Laura M.", avatar: "https://picsum.photos/seed/avatar32/50/50", rating: 5, comment: "Beautiful area and a very comfortable stay." },
    ],
  },
  {
    id: "riverfront-mansion",
    name: "Riverfront Mansion",
    address: {
      state: "Paris",
      city: "Île-de-France",
      country: "France",
    },
    rating: 4.86,
    category: ["Riverfront", "Private Garden", "Self Checkin"],
    price: 5000,
    offers: {
      bed: "4",
      shower: "3",
      occupants: "6-8",
    },
    image: "https://picsum.photos/seed/paris-mansion-main/800/600",
    images: [
      "https://picsum.photos/seed/paris-mansion-1/1200/800",
      "https://picsum.photos/seed/paris-mansion-2/1200/800",
    ],
    description: "Elegant riverfront mansion in Paris with a private garden. Ideal for large groups seeking luxury and comfort.",
    discount: "30",
    reviews: [
      { name: "Sophia R.", avatar: "https://picsum.photos/seed/avatar33/50/50", rating: 5, comment: "Stunning property and very convenient location." },
      { name: "Max P.", avatar: "https://picsum.photos/seed/avatar34/50/50", rating: 4, comment: "Spacious and beautiful, but street parking was a challenge." },
    ],
  },
  {
    id: "ski-chalet",
    name: "Ski Chalet",
    address: {
      state: "Zermatt",
      city: "Valais",
      country: "Switzerland",
    },
    rating: 4.75,
    category: ["Mountain View", "Ski Access", "Fireplace"],
    price: 3900,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-5",
    },
    image: "https://picsum.photos/seed/ski-chalet-main/800/600",
    images: [
      "https://picsum.photos/seed/ski-chalet-1/1200/800",
      "https://picsum.photos/seed/ski-chalet-2/1200/800",
    ],
    description: "Cozy ski chalet in Zermatt with direct ski access and panoramic mountain views. Perfect for winter sports enthusiasts.",
    discount: "",
    reviews: [
      { name: "John D.", avatar: "https://picsum.photos/seed/avatar35/50/50", rating: 5, comment: "Amazing ski trip! The chalet was perfect for our group." },
      { name: "Sarah L.", avatar: "https://picsum.photos/seed/avatar36/50/50", rating: 4, comment: "Very convenient for skiing, but amenities were basic." },
    ],
  },
  {
    id: "island-paradise-villa",
    name: "Island Paradise Villa",
    address: {
      state: "Mahe",
      city: "Victoria",
      country: "Seychelles",
    },
    rating: 4.98,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 6500,
    offers: {
      bed: "5",
      shower: "5",
      occupants: "8-10",
    },
    image: "https://picsum.photos/seed/island-villa-main/800/600",
    images: [
      "https://picsum.photos/seed/island-villa-1/1200/800",
      "https://picsum.photos/seed/island-villa-2/1200/800",
    ],
    description: "Ultimate island paradise with a private beach, infinity pool, and dedicated chef. Unforgettable luxury escape.",
    discount: "60",
    reviews: [
      { name: "Mohammed A.", avatar: "https://picsum.photos/seed/avatar37/50/50", rating: 5, comment: "Beyond incredible. The best villa we've ever stayed in." },
      { name: "Fatima B.", avatar: "https://picsum.photos/seed/avatar38/50/50", rating: 5, comment: "Pure bliss. Every detail was perfect." },
    ],
  },
  {
    id: "clifftop-retreat",
    name: "Clifftop Retreat",
    address: {
      state: "Cape Town",
      city: "Western Cape",
      country: "South Africa",
    },
    rating: 4.78,
    category: ["Ocean View", "Private Pool", "Self Checkin"],
    price: 4100,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-5",
    },
    image: "https://picsum.photos/seed/clifftop-retreat-main/800/600",
    images: [
      "https://picsum.photos/seed/clifftop-retreat-1/1200/800",
      "https://picsum.photos/seed/clifftop-retreat-2/1200/800",
    ],
    description: "Stunning clifftop retreat with panoramic ocean views and a private pool. Perfect for a luxurious getaway in Cape Town.",
    discount: "",
    reviews: [
      { name: "Sipho N.", avatar: "https://picsum.photos/seed/avatar39/50/50", rating: 5, comment: "The views are out of this world! Highly recommend." },
      { name: "Thandi M.", avatar: "https://picsum.photos/seed/avatar40/50/50", rating: 4, comment: "Beautiful home, but the wind can be strong up there." },
    ],
  },
];
